config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'
  resources :restaurants
  # CRUD 
  # 1. READ 
  # 1.1 Read for ALL
  # get 'restaurants', to: 'restaurants#index'
  # # 1.2 Read for one record
  # get 'restaurants/new', to: 'restaurants#new'
  
  # get 'restaurants/:id', to: 'restaurants#show'
  # # 2. CREATE
  # # 2.1 One route to display the form (NEW)
  # # 2.2 One route to actually create the instance with the form values
  # post 'restaurants', to: 'restaurants#create'
  # # 3. UPDATE
  # # 3.1 One route to edit with a form (EDIT)
  # # 3.1 One route to update the record with values (UPDATE)
  # # 4. DELETE
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name, :address, :rating, :opening_hours
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :get_restaurant, only: [:edit, :update, :destroy, :show]
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save!
      redirect_to @restaurant
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update!(restaurant_params)
      redirect_to @restaurant
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def get_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating, :opening_hours)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantReviewer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>Update your restaurant! 🍉 </h1>
<%= form_with model: @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :address %>
  <%= f.text_field :address %><br>
  <%= f.label :rating %>
  <%= f.select :rating, (1..5) %><br>
  <%= f.label :opening_hours %>
  <%= f.text_field :opening_hours %><br>
  <%= f.submit "Create" %><br>
<% end %>

app/views/restaurants/index.html.erb
<h1>These are all our restaurants!</h1>
<%= link_to 'add a new restaurant!', new_restaurant_path %>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %>
      <%= restaurant.address %>
      <%= restaurant.rating %>
      <%= restaurant.opening_hours %>
    </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Create your restaurant! 🍉 </h1>
<%= form_with model: @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :address %>
  <%= f.text_field :address %><br>
  <%= f.label :rating %>
  <%= f.select :rating, (1..5) %><br>
  <%= f.label :opening_hours %>
  <%= f.text_field :opening_hours %><br>
  <%= f.submit "Create" %><br>
<% end %>











<%# <h1>Create your new restaurant</h1>
<form action="/restaurants" method="post">
  <label for="name">Restaurant name:</label>
  <input type="text" name="restaurant[name]">

  <label for="address">Restaurant address:</label>
  <input type="text" name="restaurant[address]">

  <label for="rating">Restaurant rating:</label>
  <input type="text" name="restaurant[rating]">

  <label for="opening_hours">Restaurant opening hours:</label>
  <input type="text" name="restaurant[opening_hours]">
  <input type="submit">
</form> %>

app/views/restaurants/show.html.erb
<%= @restaurant.name %>
<%= @restaurant.address %>
<%= @restaurant.rating %>
<%= @restaurant.opening_hours %>

<%= link_to 'Home', root_path  %>
<%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
<%= link_to 'Destroy',  @restaurant,  method: :delete, data: { confirm: 'Are you sure?' } %>